package Frontend;

import Backend.Analizadores.CounterLexer;
import Backend.Manejadores.ManejadorInterfaz;
import Backend.Manejadores.ManejadorRespuesta;
import java.awt.Color;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ldulc
 */
public class Frame_VowelCounter extends javax.swing.JFrame {
    private ManejadorInterfaz manejadorInterfaz;  
    private final Color colorExtras = new Color(248,248,255);
    private final Color colorPrincipal = new Color(245,245,245);
    private CounterLexer lexer;
    private ManejadorRespuesta manejadorRespuesta;
    
    /**
     * Creates new form Frame_VowelCounter
     */
    public Frame_VowelCounter() throws UnsupportedLookAndFeelException {
        this.cambiarApariencia();
        initComponents();
        
        manejadorInterfaz = new ManejadorInterfaz();
        txtArea_input.setLineWrap(true);
        manejadorInterfaz.setEventoPosicion(txtArea_input, txt_numeroLinea, txt_numeroColumna);
        activarDesactivarBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane_TextArea = new javax.swing.JScrollPane();
        txtArea_input = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JPn_datoPosicion = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_numeroLinea = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_numeroColumna = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btn_Calcular = new javax.swing.JButton();
        tabbedP_resultados = new javax.swing.JTabbedPane();
        panel_resumen = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Resumen = new javax.swing.JTable();
        panel_detalleVocales = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_detalleResultados_Vocales = new javax.swing.JTable();
        panel_detalleEnteros = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_detalleResultados_Enteros = new javax.swing.JTable();
        panel_detalleErrores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_detalleErrores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane_TextArea.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtArea_input.setColumns(57);
        txtArea_input.setRows(5);
        txtArea_input.setTabSize(6);
        txtArea_input.setAutoscrolls(false);
        txtArea_input.setMargin(new java.awt.Insets(4, 4, 4, 4));
        txtArea_input.setSelectionColor(new java.awt.Color(153, 204, 255));
        txtArea_input.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtArea_inputInputMethodTextChanged(evt);
            }
        });
        scrollPane_TextArea.setViewportView(txtArea_input);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Contador de Vocales");

        JPn_datoPosicion.setBackground(new java.awt.Color(238, 238, 238));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        jLabel4.setText("Linea:");

        txt_numeroLinea.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 9)); // NOI18N
        txt_numeroLinea.setText("0");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        jLabel6.setText("Columna:");

        txt_numeroColumna.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 9)); // NOI18N
        txt_numeroColumna.setText("0");

        javax.swing.GroupLayout JPn_datoPosicionLayout = new javax.swing.GroupLayout(JPn_datoPosicion);
        JPn_datoPosicion.setLayout(JPn_datoPosicionLayout);
        JPn_datoPosicionLayout.setHorizontalGroup(
            JPn_datoPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_datoPosicionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_numeroLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_numeroColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPn_datoPosicionLayout.setVerticalGroup(
            JPn_datoPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPn_datoPosicionLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(JPn_datoPosicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_numeroLinea)
                    .addComponent(jLabel6)
                    .addComponent(txt_numeroColumna)))
        );

        jPanel2.setOpaque(false);

        btn_Calcular.setBackground(new java.awt.Color(255, 204, 102));
        btn_Calcular.setText("Calcular");
        btn_Calcular.setEnabled(false);
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Calcular))
        );

        tabbedP_resultados.setBackground(new java.awt.Color(238, 238, 238));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        table_Resumen.setBackground(new java.awt.Color(238, 238, 238));
        table_Resumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Descripción", "Dato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Resumen.setAutoscrolls(false);
        jScrollPane3.setViewportView(table_Resumen);
        if (table_Resumen.getColumnModel().getColumnCount() > 0) {
            table_Resumen.getColumnModel().getColumn(0).setPreferredWidth(5);
            table_Resumen.getColumnModel().getColumn(1).setPreferredWidth(303);
            table_Resumen.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        javax.swing.GroupLayout panel_resumenLayout = new javax.swing.GroupLayout(panel_resumen);
        panel_resumen.setLayout(panel_resumenLayout);
        panel_resumenLayout.setHorizontalGroup(
            panel_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        panel_resumenLayout.setVerticalGroup(
            panel_resumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_resumenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedP_resultados.addTab("Resumen", panel_resumen);

        panel_detalleVocales.setBackground(new java.awt.Color(238, 238, 238));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        table_detalleResultados_Vocales.setBackground(new java.awt.Color(238, 238, 238));
        table_detalleResultados_Vocales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Palabra", "#Vocales", "#Línea", "#Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_detalleResultados_Vocales.setSelectionBackground(new java.awt.Color(246, 223, 152));
        jScrollPane1.setViewportView(table_detalleResultados_Vocales);
        if (table_detalleResultados_Vocales.getColumnModel().getColumnCount() > 0) {
            table_detalleResultados_Vocales.getColumnModel().getColumn(0).setPreferredWidth(7);
            table_detalleResultados_Vocales.getColumnModel().getColumn(1).setPreferredWidth(155);
            table_detalleResultados_Vocales.getColumnModel().getColumn(2).setPreferredWidth(35);
            table_detalleResultados_Vocales.getColumnModel().getColumn(3).setPreferredWidth(35);
            table_detalleResultados_Vocales.getColumnModel().getColumn(4).setPreferredWidth(35);
        }

        javax.swing.GroupLayout panel_detalleVocalesLayout = new javax.swing.GroupLayout(panel_detalleVocales);
        panel_detalleVocales.setLayout(panel_detalleVocalesLayout);
        panel_detalleVocalesLayout.setHorizontalGroup(
            panel_detalleVocalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        panel_detalleVocalesLayout.setVerticalGroup(
            panel_detalleVocalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_detalleVocalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
        );

        tabbedP_resultados.addTab("Detalle de Resultados - Vocales", panel_detalleVocales);

        table_detalleResultados_Enteros.setBackground(new java.awt.Color(238, 238, 238));
        table_detalleResultados_Enteros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Cifra", "#linea", "#columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table_detalleResultados_Enteros);
        if (table_detalleResultados_Enteros.getColumnModel().getColumnCount() > 0) {
            table_detalleResultados_Enteros.getColumnModel().getColumn(0).setPreferredWidth(7);
            table_detalleResultados_Enteros.getColumnModel().getColumn(1).setPreferredWidth(231);
            table_detalleResultados_Enteros.getColumnModel().getColumn(2).setPreferredWidth(35);
            table_detalleResultados_Enteros.getColumnModel().getColumn(3).setPreferredWidth(35);
        }

        javax.swing.GroupLayout panel_detalleEnterosLayout = new javax.swing.GroupLayout(panel_detalleEnteros);
        panel_detalleEnteros.setLayout(panel_detalleEnterosLayout);
        panel_detalleEnterosLayout.setHorizontalGroup(
            panel_detalleEnterosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        panel_detalleEnterosLayout.setVerticalGroup(
            panel_detalleEnterosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_detalleEnterosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
        );

        tabbedP_resultados.addTab("Detalle de Resultado - Enteros", panel_detalleEnteros);

        panel_detalleErrores.setBackground(new java.awt.Color(238, 238, 238));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        table_detalleErrores.setBackground(new java.awt.Color(238, 238, 238));
        table_detalleErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Palabra", "Tipo de error", "#Linea", "#Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_detalleErrores);
        if (table_detalleErrores.getColumnModel().getColumnCount() > 0) {
            table_detalleErrores.getColumnModel().getColumn(0).setPreferredWidth(7);
            table_detalleErrores.getColumnModel().getColumn(1).setPreferredWidth(141);
            table_detalleErrores.getColumnModel().getColumn(2).setPreferredWidth(60);
            table_detalleErrores.getColumnModel().getColumn(3).setPreferredWidth(30);
            table_detalleErrores.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        javax.swing.GroupLayout panel_detalleErroresLayout = new javax.swing.GroupLayout(panel_detalleErrores);
        panel_detalleErrores.setLayout(panel_detalleErroresLayout);
        panel_detalleErroresLayout.setHorizontalGroup(
            panel_detalleErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        panel_detalleErroresLayout.setVerticalGroup(
            panel_detalleErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_detalleErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
        );

        tabbedP_resultados.addTab("Detalle de Errores", panel_detalleErrores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JPn_datoPosicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane_TextArea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tabbedP_resultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane_TextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(JPn_datoPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabbedP_resultados, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        Reader reader = new StringReader(txtArea_input.getText()+"\n");//he agregado este salto de línea para que así al último bloque en caso de ser alfa#, se le cuente el número de vocales xD, esto es para evitar add un %endof{ %endof} al lexer, para repetir el código de contar vocales en caso de que numeroVocales > 0
        lexer = new CounterLexer(reader);
        
        try {
            while(lexer.yylex() != CounterLexer.YYEOF){//quizá tb ERROR... bueno auqneu si da esto debería tratarse correctamente          
                //puede que de un error por hacer girar el lexer y no invocarlo solo dos veces como lo hizo el inge [aunque más pienso que se equivocó xD]
                //o por el warning de que incorrecto hace match con "empty string" 
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR);
        }
        
        manejadorRespuesta = new ManejadorRespuesta(lexer.getListaResultadosVocales(), 
                lexer.getListaResultadosEnteros(), lexer.getListaErrores());
        
        manejadorRespuesta.setResultados(table_Resumen, lexer.getCantidadResultadosTotalesPorTipo(),
                table_detalleResultados_Vocales, table_detalleResultados_Enteros, table_detalleErrores);
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void txtArea_inputInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtArea_inputInputMethodTextChanged
        if(!txtArea_input.getText().isEmpty() || !txtArea_input.getText().isBlank()){
            btn_Calcular.setEnabled(true);
        }else{
            btn_Calcular.setEnabled(false);
        }
    }//GEN-LAST:event_txtArea_inputInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_VowelCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_VowelCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_VowelCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_VowelCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frame_VowelCounter().setVisible(true);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Frame_VowelCounter.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
   /*debe invocarse antes del método init, sino da error*/
      public void cambiarApariencia() throws UnsupportedLookAndFeelException{
         this.getContentPane().setBackground(colorPrincipal);
         
        try{ 
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName()); 
        }catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e ){ 
           System.err.println("Imposible cargar interfaz, se usará la interfaz por defecto de Java.\nError: "+e);
        }         
    }    
      
      private void activarDesactivarBoton(){
            txtArea_input.getDocument().addDocumentListener(new DocumentListener() {
  
            @Override
            public void changedUpdate(DocumentEvent e) {
                updated();
            }            
            @Override
             public void removeUpdate(DocumentEvent e) {
                updated();
            }
            @Override
             public void insertUpdate(DocumentEvent e) {
                updated();
            }

            public void updated() {
                btn_Calcular.setEnabled(!txtArea_input.getText().isEmpty() ||  !txtArea_input.getText().isBlank());
            }
            });

      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPn_datoPosicion;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel_detalleEnteros;
    private javax.swing.JPanel panel_detalleErrores;
    private javax.swing.JPanel panel_detalleVocales;
    private javax.swing.JPanel panel_resumen;
    private javax.swing.JScrollPane scrollPane_TextArea;
    private javax.swing.JTabbedPane tabbedP_resultados;
    private javax.swing.JTable table_Resumen;
    private javax.swing.JTable table_detalleErrores;
    private javax.swing.JTable table_detalleResultados_Enteros;
    private javax.swing.JTable table_detalleResultados_Vocales;
    private javax.swing.JTextArea txtArea_input;
    private javax.swing.JLabel txt_numeroColumna;
    private javax.swing.JLabel txt_numeroLinea;
    // End of variables declaration//GEN-END:variables
}
